# Minimal starter Brewfile (install only; no prune)

# --- formulae ---
brew "cloudflared"
brew "mas"
brew "pyenv"
brew "sqlite"
brew "zsh-syntax-highlighting"

# --- casks ---
cask "appcleaner"
cask "arq"
cask "calibre"
cask "carbon-copy-cloner"
cask "daisydisk"
cask "discord"
cask "ente-auth"
cask "fastmail"
cask "fission"
cask "handbrake-app"
cask "iina"
cask "iterm2"
cask "jellyfin"
cask "keepassxc"
cask "makemkv"
cask "meta"
cask "name-mangler"
cask "orbstack"
cask "pastebot"
cask "signal"
cask "sublime-merge"
cask "tinymediamanager"
cask "transmission"
cask "transmit"
cask "visual-studio-code"
cask "windscribe"